version: "3.9"

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node express api
  api:
    build: .
    ports:
      - 80:3000
    environment:
      NODE_ENV: production
      DB_STRING: mongodb://mongo_db:27017/panel
      DB_STRING_PROD: mongodb://mongo_db:27017/panel
      db_name: my_db
      PORT: 3000
      SERVER_URL: http://localhost:5000/
      EMAIL_SERVICE: hotmail
      EMAIL_USERNAME: contact@vima.team
      EMAIL_PASSWORD: 2022Vim@a
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
