version: "3.9"

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node express api
  api:
    build: .
    ports:
      - 80:3000
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_STRING: ${DB_STRING}
      DB_STRING_PROD: ${DB_STRING_PROD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      SERVER_URL: ${SERVER_URL}
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
